### ISSUE TITLE
[ Animation ] conflict with scene animations

### ISSUE THREAD

**Issue by tperraut** [pixsight/SceneManager#6]
When switching scene to quickly, the animation of the second scene is ignored.

Step to reproduce with `fade` animation :
- Create 2 scene (`Scene.MAIN` and `Scene.SPINNER` for example)
- Switch them really quickly like
```kotlin
// Wait full load of the activity main scene and do this
SceneManager.scene(this, Scene.SPINNER)
SceneManager.scene(this, Scene.MAIN)
```
The `Scene.MAIN` will show up instantly instead of **fading in** and during the **fading out** animation of `Scene.SPINNER`

Step to reproduce wit `translate_x` animation :
- Create 2 scene (`Scene.MAIN` and `Scene.SPINNER` for example) with a view that is shared
```kotlin
// With your SceneCreator builder
.add(Scene.MAIN, R.id.shared_text
.add(Scene.SPINNER, R.id.shared_text)
```

- Switch them quickly
```kotlin
// Wait full load of the activity main scene and do this
SceneManager.scene(this, Scene.SPINNER)
SceneManager.scene(this, Scene.MAIN)
```
The `Scene.MAIN` will show up instantly but the **shared_text** will just go out of the screen and never come back due to the translation animation of `Scene.SPINNER` finishing, the translation animation of `Scene.MAIN` is never made for the **shared_text**

**Comment by pixsight** [comment]
Fixed with #8
